### ISSUE TITLE
Wireless connectors consuming an insane amount of power

### ISSUE THREAD

**Issue by F4ndroid** [bdew/ae2stuff#129] opened 2017-03-10 07:22 UTC
So much so that it drains the AE network entirely almost instantly when linked. The power consumption doesn't appear to be limited at all; it drained 50000000RF in around a minute. No idea how it managed this.

bdlib 1.12.3.22
AE2stuff 0.6.0.7
AE2 rv4 alpha 11

**Comment by bdew** [comment] 2017-03-13 08:23
At what distance those wireless connectors were?

The power usage formula by default is: 10 + (distance in meters)^2 AE/t

**Comment by F4ndroid** [comment] 2017-03-13 16:18
110m
How about 10+(2m)? Squaring it will cause issues like this.

**Comment by ph1x3r** [comment] 2017-04-14 23:09
I can confirm this is happening.

You connect up the first block, bind the setup tool to it and all is OK.

Then you go only a hundred or so blocks away and place the second block. As soon as you link the two, then the ME system just dies.

I have a Draconic Evolution T5 power system and use the Wyvern I/O crystals to transfer power, but nothing. Dead system.

**Comment by FairleyC** [comment] 2017-04-21 22:18
I'd like to point out the math:

Formula: 10 + 110^2 = 12,110 AE/t
AE->RF: 2 * 12,110 AE/t = 24,220 RF/t
Tick->Sec: 20 * 24,220  = 484,400 RF/s
Sec->Min: 60 * 484,400 =  29,064,000 RF/m

So in otherwords yes, a single ~100m connection would drain 50,000,000 RF it about a minute and a half.

**Comment by bdew** [comment] 2017-10-12 16:53
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Closed as completed by bdew** 2017-10-12 16:53 UTC

**Comment by staviq** [comment] 2020-04-26 06:05
I'd like to reopen this issue.

Because even if you are capable of providing that amount of power ( which is not a problem in enigmatica 2 expert, for example ), whole system dies instantly anyway.

There are some obvious problems with energy transfer, and the workaround is to add dense energy cell next to whe wireless connector.

Note, that the energy cell will not drop in power, it is not used, since i can provide more energy that is needed. The problem is in the internal buffering / transfer rates.

I propose that you either improve internal power buffer of the wireless connector OR add an "inventory" to the wireless connector, that will accept AE2 energy cells ( personally i like the second one better )

**Comment by KriKri98** [comment] 2020-06-07 15:56
I have a similar issue. I`m on MC Eternal.

I have an Flux Point (on Mekanims Induction Cell, IO 65MRF/t) on my system for power. This system draws around 1.5kRF/t, even with an connector at around 10m away, the connector says it needs 256 rf/t, but my system power draw is up to 2kRF/t. When I place them further apart they state, that they need 28kRF/t, but my Flux Point puts 170kRF/t in the system. And somehow the system even if I could provide enough power.

**Comment by Terkonzer** [comment] 2020-11-15 20:59
can't you like, configurate it so it doesn't consume so much flippin power
