### ISSUE TITLE
[Bug] Advanced Inscriber took items without giving an output.

### ISSUE THREAD

**Issue by Endermod** [bdew/ae2stuff#57] opened 2015-08-10 12:09 UTC
Diamonds. :(

**Comment by bdew** [comment] 2015-08-10 12:22
Does it have enough power to run? It consumes items at the start of the operation (unlike AE2 inscriber).

Also what versions of both mods?

**Comment by KitStead** [comment] 2015-08-13 13:24
I had the same. Definitely enough power. Running appliedenergistics2-rv2-stable-10 with ae2stuff-0.4.3.47-mc1.7.10

**Comment by bdew** [comment] 2015-08-16 06:04
I've tried and can't reproduce this.

Did it start processing then didn't gave an output? Or did it just took the items whith the progress bar not moving?

**Comment by KitStead** [comment] 2015-08-16 06:10
As soon as the item was placed in, it was consumed. The front animation happened instantly and quick. Then nothing. No output. I had pipes attached (thermal dynamics) with and without servos. Nothing entered the pipe system and nothing was returned when the inscribers or pipes where broken.

**Comment by Icepick869** [comment] 2015-10-04 19:17
KitStead - Do you have items being grabbed up from the Adv Inscriber with an Import bus to you AE2 system?

I've been having an issue where it will produce a handful of the requested items, then the import bus pulls the output items (stopping the operation) and when it takes the last item it doesn't give the inscriber back the operation unless you remove the bus. This seems like it could be the same one, except you don't mention the import bus.

I've tried a number of work arounds, including a Thermal Energistics Item duct with Hardened servo, but it still locked up.

If this isn't the same problem please let me know so I can open a bug report on it.

**Comment by bdew** [comment] 2015-10-04 21:32
Busses don't supply power, neither do microblock interfaces. Full block interfaces supply power but only if they aren't "pointing" at the block.

To be be clear, your input bus issues were fixed by running a separate power line to the inscriber?

**Comment by Icepick869** [comment] 2015-10-05 10:04
Yes. Also I discovered after the post that I still had the issue with just the interface attached. It was what led me to try the separate line.

**Comment by bdew** [comment] 2017-10-12 16:44
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Closed by bdew** 2017-10-12 16:44 UTC

**Comment by SonarSonic** [comment] 2018-03-16 21:19
Same issue on 1.12.2

**Comment by phlaxyr** [comment] 2018-06-21 19:27
Mine is stuck in the middle of it being processed - it stopped at 96%
