### ISSUE TITLE
Wireless Connector Dissappearing

### ISSUE THREAD

**Issue by LokeYourC3PH** [bdew/ae2stuff#95] opened 2016-01-10 14:08 UTC
So, on my Galacticraft Space Station i have a large AE System. Im using a lot of Wireless Connectors, but since i updated to the latest version (0.5.1.61), the Wireless Connectors have been dissappearing randomly once the dimension is unloaded or the server reboots. There is no log for this, as just about 2-4 of them sometimes arent there when the server reboots or the dimension has been unloaded.

**Comment by bdew** [comment] 2016-01-10 17:22
That's odd. I'll look into this.

Can you confirm if going back to 0.5.1.59 stops this issue?

Added: is there a security station on the network?

**Comment by LokeYourC3PH** [comment] 2016-01-10 21:22
Yes, there is a security station on the network.

And i can try later to go back to 0.5.1.59 to see if it stops :)

**Comment by LokeYourC3PH** [comment] 2016-01-10 21:25
Also, something else is bothering me with the Wireless Connectors to. Its the fact that if i have to many Wireless Connectors hooked to my ME System, and some have a big longer range, like 30-50 blocks or so, when the space station dimension is unloaded and reloaded, the AE System seizes to work. I actually have to entirely disconnect the Wireless Connectors their Dense ME Cables, or else the ME System (even with a Creative Power Source) will stop working, and just show its offline, but when disconnecting two or three random Wireless Connectors, the AE System starts working again. Then i can reconnect the Wireless Connectors. Then, maybe 10 minutes later or so, the same thing happens. I dont know what causes it, but im sure it cant be power loss, atleast not when i have multiple creative power sources hooked up to the system.

**Comment by bdew** [comment] 2016-01-20 08:16
I've tried and couldn't reproduce either issue.

Did you try going back to .59? i'm trying to pinpoint what changes could be involved in this and knowing at what version it broke would make it a lot easier.

**Comment by LokeYourC3PH** [comment] 2016-01-20 21:57
You can try with my modpack if you like, you find it by looking for "SG-B 248M" in the TechnicLauncher. Anyways, i did try going back to 59 and it didnt happen then, so i dont know.

**Comment by bdew** [comment] 2017-10-12 16:45
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Closed as completed by bdew** 2017-10-12 16:45 UTC
