### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LeiserGeist** [bdew/ae2stuff#75] opened 2015-09-30 08:24 UTC
When a user in our server placed a pattern inscriber between the 64k storage blocks of two AE2 crafting CPU pillars (http://i.imgur.com/qP7scoC.png), the server crashed with the following error:

http://www.hastebin.com/arojuhicog.avrasm

I'm unsure if the error is indeed due to ae2stuff but it shows up in the stack trace a few times.

**Comment by bdew** [comment] 2015-09-30 09:09
Doesn't look like an error on my side. It shows up in the log because it tried to join the AE2 network, and something broke in AE2.

Does it crash if you try to place it there again or was it a once-off thing?

**Comment by LeiserGeist** [comment] 2015-09-30 09:36
Now that's speedy service!
The crash happened twice but I told the guy to steer clear of the block space it happened in, lol
It hasn't happened since.
I'll try to reproduce it and see, but we're having terrible luck with our server crashing today so I'll get back to you in a few years when Gregtech loads

**Comment by bdew** [comment] 2015-09-30 10:54
By the way - What version of both AE2 and AE2 Stuff?

**Comment by LeiserGeist** [comment] 2015-09-30 11:26
Ah yes, sorry about that.
MC 1.7.10
Forge 1492
AE2 rv2-stable-10
ae2stuff-0.5.0.56

**Comment by bdew** [comment] 2015-09-30 21:49
I've played with it a bit and couldn't reproduce the error. Is there anything else special going on around there with network topology?

> Edit2: It doesn't happen with any other AE2 machine, or any others from your mod, just your pattern encoder

That's really odd. I don't think the pattern encoder is doing anything differently than the other blocks in the mod.

> Edit3: Apparently if you break the encoder, it also destroys the pattern contents? I dunno, just something someone mentioned

It should store whatever was inside in the block when broken, and still be there when placed back.

**Comment by LeiserGeist** [comment] 2015-10-01 08:30
I have no idea. The guy's base is frankly a mess so it's possible, but the AE system looks like a run of the mills late-game system.

It hasn't happened since, but next time I'm around the server I'll try that.

**Comment by LeiserGeist** [comment] 2015-10-08 06:58
Haven't come across the issue since. Thanks for your replies!

**Comment by bdew** [comment] 2015-10-08 07:12
Ok i'm closing it for now. If you get more information or it happens again comment here or open a new issue.

**Closed by bdew** 2015-10-08 07:12 UTC
