### ISSUE TITLE
AE2stuff Inscriber vanishes -version: ae2stuff-0.6.0.9-mc1.10.2

### ISSUE THREAD

**Issue by LightSyaoran** [bdew/ae2stuff#131] opened 2017-03-20 17:18 UTC
Hello, 

So i've been using the Ae2stuff Inscirbers and they have been dissapearing from my server world after a while of being up, a while being a few hour to a few days.

Pack: FTB Beyond
Version: ae2stuff-0.6.0.9
Minecraft: 1.10.2
AE2: rv4-alpha-11

**Comment by bdew** [comment] 2017-03-20 17:46
Is there anything fishy in the logs around the time they disappear? Are the areas they are in chunkloaded in any way? Do all of them disappear or only some?

Need more details, not much to go off here...

**Comment by LightSyaoran** [comment] 2017-03-20 19:30
The logs don't show anything and the area's are chunkloaded using ftbu, the last few days it was just 1 dissapearing and then when i came on today all of them were gone so they may have dissapeared 1 at a time, it's kind of like they break since the first 2 i had go in to my inventory at random with a magnet ring.

They are also connected to a import ME Import Bus and a ME Interface for auto-crafting.

hope that is enough info... not sure what else i could say...

**Comment by LightSyaoran** [comment] 2017-03-21 14:46
okay so i just did a test to see what's happening and left them all night and put up a Vacuum Chest as well, it collected the AE2stuff Inscribers during the night, so i'm guessing they are just breaking somehow, 6 of them were on top of each other and the 7th was solo.

**Comment by DoomSquirter** [comment] 2017-03-28 17:55
Just to leave my 2 cents in here.  Having a problem exactly like this on another pack.  latest versions of everything.  FTButils is also in pack and is only chunkloader we're currently using atm.  We are adding another to test to see if problem still occurs with that in use as well.

One additional thing tho.  When the items drop into the world, they lose all their contents.  That might be important to note.  all cards, any resources inside (i.e. plates or silicon/redstone).  

Lastly, on a related note, the same time this happens, which seems to be every time the server reboots, I lose flying functionality from envirotech nanobots on a random basis and to resolve this problem, I have to unclaim/chunkload and reclaim/chunkload all my chunks with ftbutils and the envirotech problem goes away, and I don't seem to have recurring issues with ae2stf disappearing after that, till next reboot.

edit: just wanted to state tho that the only 2 issues that occur are the ae2stuff stf disappearing and the envirotech stf acting strange.  The problem might very well end up in ftbutils court to fix but ae2stf is definately affected somehow unlike other mod items that aren't (cept envirotech).  Once we have another chunkloader to test against, I was planning on creating issues all around to note the problem.

**Comment by DoomSquirter** [comment] 2017-03-31 15:34
so a followup.  added chunkloaderz to pack.  Yesterday I had made mine but they expire in 9 hours.  Logged in this morning to find that my ae2stuff gear had all dropped again as a result.  

FTButils is still in the pack but I had removed all owned chunks and removed chunkloading from those tiles as well.  The only thing handling the chunkloading was chunkloaderz.

**Comment by DoomSquirter** [comment] 2017-03-31 16:34
An additional piece of information.  

So, on the server, of the 6 or so ppl that are playing, a couple others have ae2stuff setup in their bases.  One person that I know of has the same issue with chunkloading that I have (away from base, ftbutils stops chunkloading base).  But, he's not having his ae2stf gear drop as items.  

All my ae2stf gear is in same chunk as my ae system, in same room which is the size of a chunk.  So even tho it's not helpful, it's still peculiar trying to understand how it's happening to me and not them.

**Comment by bdew** [comment] 2017-04-01 00:31
Does either of you have a security station on the network? Does adding/removing one affects the issue in any way?

I'm suspecting some weirdness in code related to security/ownership, though i haven't manage to figure out exactly what's going wrong.

**Comment by LightSyaoran** [comment] 2017-04-01 01:08
i have one on my network but i'm pretty sure i added it after i posted this bug, i can give it a test though.

I've tested it while being at least 1 to 2 chunks away at most and it has dissapeared during that time so not 100% sure on the chunkloading/unloading stuff, i will try another chunk that it's never been in though just to see if it could be a chunk problem.

**Comment by jusvit** [comment] 2017-04-09 14:42
Having this problem as well, seems to have started happening after I've put the security console down. The inscribers drop on the floor instead of vanishing ( losing contents)

**Comment by jusvit** [comment] 2017-04-10 02:27
Temp fix: power the inscribers with a separate network and use a chest as a buffer for the interface.

**Comment by DoomSquirter** [comment] 2017-04-10 08:23
I had a security station before anything happened.  No security was added (nobody added, etc)  it was just added for access to wireless.

**Comment by laurad2423** [comment] 2017-04-11 19:07
Having this issue as well. I have a security station. I am on FTB Beyond on a server. Started off with just pattern encoder, then started with Advanced inscribers, and now even the growth chamber too. All contents gone. currently picking them up with a magnet hopper. 

I will mention that a certain spot where I had the Advanced inscriber (AI) no longer allows me to place the AI. Every time i place it, it immediately breaks in place, like i'm assuming is happening when i'm not around with the others.

**Comment by laurad2423** [comment] 2017-04-11 19:10
![2017-04-11_12 07 37](https://cloud.githubusercontent.com/assets/27070673/24926244/d9b0c04e-1eaf-11e7-8075-9cecd572afd8.png)
![2017-04-11_12 08 02](https://cloud.githubusercontent.com/assets/27070673/24926245/dbc24d8a-1eaf-11e7-874f-72bccc121aee.png)
![2017-04-11_12 08 03](https://cloud.githubusercontent.com/assets/27070673/24926238/d28de9c2-1eaf-11e7-9ea7-1f438d566d67.png)
Attached are Screenshots of the inscriber that breaks as soon as you place it.

Also note that the basic inscribers were all Advanced inscribers that i had to downgrade because of how frustrating it was having to replace them all the time

**Update** I disconnected any me connections and just gave them power via quartz fiber and I can now place the inscriber in place again.

**Comment by LightSyaoran** [comment] 2017-04-11 19:17
i've done a bunch of tests and so far no matter where i moved it the items would break with a security console attached, however so far without the sercurity console it has not broken yet, so i'm guessing it's something to do with the security console, however i guess i wont be using a wireless controller while the bug is here =p

**Comment by laurad2423** [comment] 2017-04-11 19:22
@LightSyaoran I'm going to try to just keep my AE2 stuff power by quartz fiber, but not on the network. maybe that will work so you can keep your wireless.

**Comment by andremiller** [comment] 2017-04-16 18:41
Could this also be related to chunkloading / unloading - there's a similar issue logged #136 for Wireless connectors that happens during chunkloads.

**Comment by boogieman1402** [comment] 2017-04-17 18:19
Just to add my observation: i had some advanced inscribers break on me. In this situation, there was a Security terminal in a chunkloaded chunk. The Inscribers were in a chunk that wasn't loaded. 

Interestingly enough, only 4 of the 5 inscribers broke, the ones with presses inserted. The 5th was empty and was unaffected. 3 of the 4 broken inscribers were not connected to any ME cables, only to each other and one central interface (the fifth strictly speaking wasn't connected either, it had an enderIO ME Conduit running behind it to connect the Interface)
AIA
AAA (A=Inscriber, I=Interface)

After I made sure the chunk with the Inscribers was also loaded, I haven't seen them break anymore.

Finally, not sure if this is somehow related, but I was unable to place the Inscriber that had the ME Conduit running behind it. It would place and instantly break, had to route the cable slightly differently.

And just for the sake of completeness: we were running FTBBeyond 1.5.3 when all this occured, with ServerSidedChunkLoader (0.3.2) added because FTBU chunkloading was acting funky.

**Comment by MrNinja93** [comment] 2017-05-24 23:32
Only just had this issue myself, been slow on getting wireless AE/Security Terminal, playing Beyond.

Notice people mentioning chunkloading so did some testing, FTB Utilities fails to stop the blocks breaking but Extra Utilities2 chunk loading ward stops the "unload" and breaking of inscribers/growth chambers from happening

**Comment by heyoomimi** [comment] 2017-07-23 17:38
I'm also experiencing this issue as well. I'm running a custom modpack but we are using FTBUtils and Sponge.

**Comment by laurad2423** [comment] 2017-07-23 18:21
Keep the ae2 stuff items on their own sub network. That fixes it.

**Comment by zashra00** [comment] 2017-08-03 06:24
this sounds like a sponge issue... sponge does very weird things to forge

**Comment by bdew** [comment] 2017-10-12 16:53
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Closed as completed by bdew** 2017-10-12 16:53 UTC

**Comment by NosajDraw** [comment] 2017-12-16 22:02
This error still exists in 1.12 and after much experience I can confirm that it is the security station rejecting AE2Stuff items on chunk-loading.

Work around

1) don't deploy a security station
2) Confine AE2Stuff the same chuck as the security station
3) Place AE2Stuff on its own, none security stationed subnetwork

Suspect this issue is not AE2Stuff as AE2 has had a bug about dropping items on chunk loading since 1.7, AE2Stuff just seems particularly susceptible.

**Comment by AlienChief** [comment] 2018-02-26 04:27
Still having issues in 1.12.2 with them disapearing

**Comment by DoomSquirter** [comment] 2018-02-27 17:55
so to tag this, playing ssp in a 1.12.2 pack and had this happen but it was quite obvious what the cause was.

I had quit my world (save to main menu) and came back a few minutes later and loaded world up.  noticed all my ae2stuff was gone.  but.  I also noticed that ftbutils had lost it's mind.  all my chunkloaded chunks were gone and I couldn't readd any chunks as chunkloaded.  restarted mc and everything went back to normal.  put ae2stf back and everything's fine.  

It's definately got something to do with chunkloaders, more than likely ftbutils.

**Comment by Morpheus1101** [comment] 2018-02-28 00:37
I had my Security Station on the same Cable as my Crafting, Pattern & Interface Terminals & when moved the Security Station off to another cable, it solved my issue of the inscribers(only the bottom ones) breaking when re-joining my chunk

**Comment by DoomSquirter** [comment] 2018-03-01 16:04
my sec station is connected directly to controller and inscribers connected to another part of controller but through cable.  from what others have said, moving to another network slaved out works best but tbh, I never ever have to do that.  One server on smp did this behavior and now this one on ssp but only when ftbutils lost it's mind and borked the chunkloading.  

find it wierd that ae2stf tho is only thing affected.  I have stf from extracells that aren't affected.  even in this instance.

**Comment by NosajDraw** [comment] 2018-03-01 19:27
It's not only AE2Stuff that is affected, and it's not related to FTBUtils.

It is an AE issue to do with chunkloading, the security station sees a new chunk loading and for some reason fails to recognise part of it's network as "it's" network and causes the items it rejects to drop, it does this to its own components, however for some reason AE2Stuff is particularly prone. I suspect some kind of timing/race condition.

AE2 dev are well aware of the issue, but they keep basically refusing to fix it, on one report (which I now can't find) they even suggested that to get rid of the problem the entire AE system should be build in one chunk.

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/92
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1074
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1246
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2138

**Comment by DoomSquirter** [comment] 2018-03-08 23:49
see that's the thing tho.  I'm very chunk aware and each time this has happened to me, I've built the system all in one chunk.  

yes, cables leave that chunk to connect to other places but the guts, all of the main stf are always in the same chunk.

and I've only had this happen in two packs, both had ftbutils and only things affected were the ae2stuff stuff.  

what I was inferring was that it seems like two things are at fault from my non dev perspective.  
1) ftbutils somehow messes up and doesn't load or keep loaded, the chunks you specified it to.
2) ae2stf somehow pops off the network.  

I've used ae2stf in COUNTLESS packs and have never had a problem in any of them except where noted.  I have to assume that a problem does exist in ae2stf somewhere since the behavior is only exhibited in it.  BUT, that something is triggering that behavior resulting in this odd situation.

anyways, yeah, it's sad that ae2stf is prone to this.  My fix is to just ensure good chunkloading and guess I'll just ignore the problem (and place chests with vacuum hoppers in my ae room just in case haha)

**Comment by amilliner** [comment] 2018-03-25 23:11
I had an issue with this in 1.12.2, AE2stuff 0.7.0.4, AE2 version rv5-stable-10, forge version 14.23.2.2611, FML version 8.0.99.99.

Unfortunately the server I've been playing on isn't the most stable (custom pack, has a few wrinkles left to iron out), so diligent chunkloading wasn't enough to fix my issue.

I got tired of losing acceleration cards and did some experimenting with fixes. I found that quartz fibre connections do not affect whether the AE2stuff machines pop on chunk loading, but using panel interfaces instead of full block interfaces did stop them popping. It's slightly less convenient to use panel interfaces, but it does at least seem to be a reliable fix
