### ISSUE TITLE
Network visualisation tool doesn't show anything in other dimensions

### ISSUE THREAD

**Issue by jpeaglesandkatz** [bdew/ae2stuff#123] opened 2016-12-03 13:54 UTC
Trying it in my voidbase, RFTools dimenstion and it doesn't do anything.

1.10.2
ae2stuff-0.6.0.6-mc1.10.2
bdlib-1.12.2.18-mc1.10.2

**Comment by bdew** [comment] 2016-12-04 18:51
Can't reproduce this.

What exactly are you doing? Do you get the "Visualising network at ___,___,___" message when clicking in the dimension?

**Comment by jpeaglesandkatz** [comment] 2016-12-05 19:51
I'm in a void world where my base is. It is an RFTools dimension. 

When I put the tool in the hotbar and activate it like you would normally, nothing happens and no visualising message, nothing. It doesn't show the layout of the ae2 network.

It does work in the overworld.

**Comment by bdew** [comment] 2016-12-05 20:03
Might be a stupid question, but you know that you need to (shift+)right-click a block in the network to get it to visualize, right?

If right clicking doesn't do anything please check the log for any errors or warnings after doing it.

**Comment by bdew** [comment] 2017-10-12 16:51
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Closed as completed by bdew** 2017-10-12 16:51 UTC
