### ISSUE TITLE
Infinity Duping bug with AE2 Stuff Blocks.

### ISSUE THREAD

**Issue by Speiger** [bdew/ae2stuff#132] opened 2017-03-28 17:55 UTC
A big server uses the FTB Beyond Modpack
And they were able to cause a really really big block duping bug.
Sadly i cant tell you why its happning since i cant read/write scala code.
But this seems bad.

https://gyazo.com/0d7ea09a0978b6f76d20692b64f093be
https://gyazo.com/36e22491b7497cd5e57b895c2534bd5b
Two examples.

Fast answer would be nice.

**Comment by bdew** [comment] 2017-03-29 05:50
That's... interesting. I'll look into it.

**Comment by Brend-Smits** [comment] 2017-04-04 10:25
Any luck on fixing this bug? Experiencing this as well and it seems to be a big issue

**Comment by bdew** [comment] 2017-04-04 15:33
Sorry about the delay. I've tried and wasn't able to reproduce this, i even tried to reconstruct the setups from the clips posted by @Speiger and i can't get it to happen.

Anything more specific you can give me about the setup? Are security stations involved anywhere and if so what is their settings and who placed what block?

**Comment by Brend-Smits** [comment] 2017-04-04 16:00
We use SpongeForge , could it possibly be related that a specific event is not casted or a specific event is not cancelled?

**Comment by bdew** [comment] 2017-04-05 08:02
Hm, maybe. I honestly have little experience with sponge. I wonder if i can get it running in my dev environment and check with it....

**Comment by Speiger** [comment] 2017-04-05 09:29
You can install a sponge mod or just make a new envioment with the spongeforge and your mod.

**Comment by Speiger** [comment] 2017-04-12 15:53
@bdew how are things going?

**Comment by BloodWorkXGaming** [comment] 2017-05-09 15:33
might be the same reason why #138 happens...

**Comment by bdew** [comment] 2017-10-12 16:54
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Closed as completed by bdew** 2017-10-12 16:54 UTC
