### ISSUE TITLE
Game Crash when placing a block from AE2 Stuff

### ISSUE THREAD

**Issue by modsareawesome** [bdew/ae2stuff#163] opened 2017-11-22 20:03 UTC
The Game keeps crashing when placing a block. After restarting Minecraft the Block is placed and works fine. It just crashes when placing it. Doesnt matter if Crystal Growth Chamber or Advanced Inscriber and whatever.

**Comment by bdew** [comment] 2017-11-23 05:47
Dupe of #164

**Closed as completed by bdew** 2017-11-23 05:47 UTC
