### ISSUE TITLE
[Feature Request] Compatibility with Mekanism Energy Cables

### ISSUE THREAD

**Issue by FREEZEball** [bdew/ae2stuff#31] opened 2015-06-08 12:31 UTC
Title says it all. Players can use Energy Cables to supply power to AE2 Inscribers, but you need Energy Acceptor or ME Cable to feed AE2Stuff ones.

**Comment by bdew** [comment] 2015-06-08 14:39
This is how it's intended - they take power from AE network only. Also duplicate of #27

**Closed by bdew** 2015-06-08 14:39 UTC
